### ISSUE TITLE
0.8.1 to 0.8.3 migration does not work

### ISSUE THREAD

**Issue by amanenk** [cloudquery/cq-provider-aws#362]
### Describe the Bug

 migration aws provider from 0.8.1 to 0.8.3 causes next error
 ❌ Failed to upgrade provider /cq-provider-aws@latest. Error: migration failed: column "arn" of relation "aws_ec2_subnets" already exists in line 0: ALTER TABLE IF EXISTS "aws_ec2_subnets"     RENAME COLUMN "subnet_arn" TO "arn"; (details: pq: column "arn" of relation "aws_ec2_subnets" already exists).

### Expected Behavior

migration should work.

**Comment by yevgenypats** [comment]
Can we catch those kind of bugs in CI ?

**Comment by roneli** [comment]
> Can we catch those kind of bugs in CI ?

We have migration tests that run from first migration to last each merge. This will occur if you changed the table before the migration etc' I think this is an issue in @amanenk local deployment rather than the migration itself. That being said we should add the `IF NOT EXISTS` keyword to the migration

**Comment by amanenk** [comment]
I have tired to reproduce it but I it didn't appear again. I confirm that it was related to a broken local database

**Comment by roneli** [comment]
Fixed in migration test fix
