### ISSUE TITLE
Support Fetching Via AWS Organizations

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#442]
We support fetching data about Organizations, but we do not support traversing an OU structure to fetch data.

A customer should be able to specify An OU path and  A Role name and we should traverse the OU structure fetching data using the provided role.

caveat:
- The initial credentials must belong to an admin account

**Comment by paul-e-allen** [comment]
In my situation, I'd be happy just to cycle over all the linked accounts, regardless of AWS Org OU structure. Scoping by OU structure would be icing on the cake.

Since the roles to assume would belong to each linked account, I think we'd need a Role name or Role pattern, not a whole Role ARN to use in each linked account. E.g. the standard Org access Role in linked accounts is `OrganizationAccountAccessRole`, but we would not want to use that since it allows full access, not read-only. In my situation we have standardized that each linked account also contains a Role named `OrganizationAccountReadOnlyAccessRole` that provides just read privs from the master account. So, I would specify that CQ use that role name.

**Comment by bbernays** [comment]
If path filtering adds significant scope to the work we will definitely release a version without it and assume that we should just traverse the whole org

We will allow users to specify a role to assume in the admin account and then a separate role to assume in the member accounts. The member account role names, do you need that to be templated or do all accounts have a role with the same name?

**Comment by paul-e-allen** [comment]
In my case, those role names are standardized, just just  single role name for all the linked accounts would suffice.
